### ISSUE TITLE
Save masked image as transparent PNG

### ISSUE THREAD

**Issue by cduk** [Uminosachi/inpaint-anything#18]
This tool would be great for selecting parts of the image and then saving as a PNG with the unmasked parts treated as transparent. Would it be possible to add this transparency feature?

**Comment by Uminosachi** [comment]
Supported that feature in v1.5.1. It can be accessed by clicking the `Get mask as alpha of image` button under the `Mask only` tab.

**Comment by cduk** [comment]
I use the following script to create the transparent PNG. It's not as convenient as having the feature within inpaint-anything, but it works:

#!/usr/bin/python3
import sys

total = len(sys.argv)
cmdargs = str(sys.argv)

if total!=3:
    print ("Usage: %s image mask " % sys.argv[0])
    sys.exit()

from PIL import Image, ImageOps

# load images
#img_org  = Image.open('target.png')
#img_mask = Image.open('mask.png')
img_org  = Image.open(sys.argv[1])
img_mask = Image.open(sys.argv[2])

# convert images
img_org  = img_org.convert('RGBA') # or 'RGBA'
img_mask = img_mask.convert('L')    # grayscale
img_mask = ImageOps.invert(img_mask)

# add alpha channel    
img_org.putalpha(img_mask)

# save as png which keeps alpha channel 
img_org.save('output.png')
