### ISSUE TITLE
Inpaint doesn't take prompt

### ISSUE THREAD

**Issue by daffatahtaa** [Uminosachi/inpaint-anything#22]
hello, so I found this extension through youtube and I'm interested to try it out. So I've downloaded the model, I've inserted the image but when I fill the prompt in Inpaint and click run inpainting it only gives masked area as an output.

1. Model
![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/5cff7a2d-22ff-4c0c-981b-cfe27d19bbcc)

2. Inpaint prompt + Mask selection
![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/fbdfb61a-2f48-4ba5-bf0b-8a707bd20d35)
![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/21681bbe-305a-430f-a9cc-901f507c3318)

3. Result + CMD
![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/8b3fad76-706b-411e-bc30-9d9377f66f66)
![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/77b4cf38-cb49-4ee7-9929-335eea92a226)

Please help, am I  missing something?

**Comment by Uminosachi** [comment]
Have you tried inpainting with other models in the model dropdown list to verify if they yield the same results?
The model you downloaded is typically stored in your home directory. You can locate it at `/home/username/.cache/huggingface/hub` for Linux and MacOS users, or at `C:\Users\username\.cache\huggingface\hub` for Windows users. It's possible that the model you're currently using may be corrupted.

**Comment by daffatahtaa** [comment]
I've tried to use another model from the dropdown

![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/ad6b9162-5b1f-4bb3-a215-aec83f5cce02)

The result are the same. I also put --xformers into my SD launch command

**Comment by Uminosachi** [comment]
The some package may be outdated. I recommend deleting the `venv` folder located within the stable-diffusion-webui directory, and then rerunning `webui.bat` or `webui.sh`. This will reinstall the package from scratch.

**Comment by daffatahtaa** [comment]
Not working still, I've deleted my old venv folder and reinstall it again.

![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/50de18fa-f865-46a9-99d4-cc85e696bcf9)

![image](https://github.com/Uminosachi/inpaint-anything/assets/43267539/1657b240-51d6-4f8b-9c92-4b8ffb037586)

**Comment by daffatahtaa** [comment]
Good news, somehow it worked just now. Idk how I fixed that lol
