### ISSUE TITLE
how to change / custom  Model ID (run inpanting) ? 

### ISSUE THREAD

**Issue by EKI-INDRADI** [Uminosachi/inpaint-anything#24]

**Comment by Uminosachi** [comment]
If you place a model with the 'safetensors' extension and 'inpaint' (case-insensitive) in its filename into the `stable-diffusion-webui/models` directory, it will appear under the Model ID section of the 'Inpainting webui' tab.

**Comment by Uminosachi** [comment]
The standalone version of Inpaint Anything does not support 'safetensors' file. Please use the web UI extension version.

**Comment by ENTPRESTIGIOUS** [comment]
> If you place a model with the 'safetensors' extension and 'inpaint' (case-insensitive) in its filename into the `stable-diffusion-webui/models` directory, it will appear under the Model ID section of the 'Inpainting webui' tab.

It doesn't work. The program just hangs.
