### ISSUE TITLE
Support Torch 2.1.0

### ISSUE THREAD

**Issue by ashleykleynhans** [Uminosachi/inpaint-anything#26]
The requirements.txt file specifies `torch==2.0.1`. but may be better just to specify `torch` without locking it into a version number.

**Comment by Uminosachi** [comment]
As of now, we haven't found a version of xformers that is compatible with torch 2.1.0. For this reason, I'll postpone the update in requirements.txt.

**Comment by Uminosachi** [comment]
This issue will be closed as the versions in the `requirements.txt` have been upgraded: `torch` to 2.2.2 and `xformers` to 0.0.26.
