### ISSUE TITLE
Features Missing from Img2Img?

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [Uminosachi/inpaint-anything#29]
Where is the resize mode option?

**Comment by ENTPRESTIGIOUS** [comment]
Batch Size and Batch Count also seems to be missing!

**Comment by Uminosachi** [comment]
> Where is the resize mode option?

Currently, this app does not support resizing of the input image.
However, it does support resizing with padding.

> Batch Size and Batch Count also seems to be missing!

You can set the number of iterations using the `Iterations` slider located below the `Run Inpainting` button.

> I feel like Guidance Scale should be named CFG Scale

"Guidance" is derived from "Classifier Free Guidance", so I believe you understand its meaning.

**Comment by ENTPRESTIGIOUS** [comment]
> Currently, this app does not support resizing of the input image. However, it does support resizing with padding.
Can this be implemented in the future? What is resizing with padding? What does that do? How do I use it?

> You can set the number of iterations using the `Iterations` slider located below the `Run Inpainting` button.
Right thanks! First time using it so yeah, not used to the different terminology for the GUI.

> "Guidance" is derived from "Classifier Free Guidance", so I believe you understand its meaning.
Aight ok.

**Comment by Uminosachi** [comment]
> Can this be implemented in the future? 

There are no plans to implement simple resizing.

> What is resizing with padding? What does that do? How do I use it?

Resizing with padding can be accessed by opening the `Padding options` accordion located below the Input image area.

> Also, is there a way to export the inpaint mask created using the SAM so I can import it to Img2Img inpaint perhaps?

With the SD webui [extension version](https://github.com/Uminosachi/sd-webui-inpaint-anything) of Inpaint Anything, you can directly send the mask image to img2img by clicking on `Get mask` under the `Mask only` tab, then `Send to img2img inpaint`.

**Comment by ENTPRESTIGIOUS** [comment]
> With the SD webui [extension version](https://github.com/Uminosachi/sd-webui-inpaint-anything) of Inpaint Anything, you can directly send the mask image to img2img by clicking on `Get mask` under the `Mask only` tab, then `Send to img2img inpaint`.

Ok thanks!
