### ISSUE TITLE
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [Uminosachi/inpaint-anything#30]
Is there a fix for this? I tried to add Loras but this shows up in my terminal!

**Comment by Uminosachi** [comment]
This is due to a limitation in the diffusers package used internally, which restricts prompt lengths to 77 tokens.
Additionally, LoRA is not usable in the Inpainting tab.

**Comment by ENTPRESTIGIOUS** [comment]
> This is due to a limitation in the diffusers package used internally, which restricts prompt lengths to 77 tokens. Additionally, LoRA is not usable in the Inpainting tab.

Is there a way to bypass this? Will there be a plan to be able to include LoRA in the future?

**Comment by Uminosachi** [comment]
> Is there a way to bypass this?

I believe reducing the number of words in the prompt will remove the warning.

> Will there be a plan to be able to include LoRA in the future?

I currently have no plans to support LoRA.

**Comment by ENTPRESTIGIOUS** [comment]
> I believe reducing the number of words in the prompt will remove the warning.

Alright.

> I currently have no plans to support LoRA.

Ok.
